module.exports = {
    upgrader:[
        {work:1,carry:1,move:2},
        {work:2,carry:2,move:2},
        {work:4,carry:4,move:4},
        {work:6,carry:6,move:6},
        {work:9,carry:9,move:9},
        {work:10,carry:12,move:11},
        {work:15,carry:15,move:15}
    ],
    harvester:[
        {work:1,carry:1,move:1},
        {work:5,move:1},
        {work:6,move:3},
        {work:6,move:3},
        {work:10,carry:4,move:5},
        {work:10,carry:4,move:5},
        {work:10,carry:4,move:5},
        {work:10,carry:4,move:5},
        {work:20,carry:8,move:10}
    ],
    filler:[
        {carry:4,move:2},
        {carry:6,move:3},
        {carry:10,move:5},
        {carry:16,move:8},
        {carry:24,move:8},
        {carry:30,move:15},
        {carry:32,move:16},
        {carry:32,move:16}
    ],
    centerManager:[
        null,
        null,
        null,
        {carry:16,move:8},
        {carry:24,move:8},
        {carry:30,move:15},
        {carry:32,move:16},
        {carry:32,move:16}
    ],
    transfer:[
        {carry:4,move:2},
        {carry:6,move:3},
        {carry:10,move:5},
        {carry:16,move:8},
        {carry:24,move:8},
        {carry:30,move:15},
        {carry:32,move:16},
        {carry:32,move:16}
    ]
}